AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
#
#Naming/MethodParameterName:
#  AllowedNames: [as]

Layout/LineLength:
  Max: 120
